### ISSUE TITLE
Poor results on synthetic dataset.

### ISSUE THREAD

**Issue by GostInShell** [momentum-robotics-lab/deformgs#6]
Hi! I run your code on the synthetic dataset `scene1`. In the coarse stage, it still produce blurry results after 8000 iteration, which seems not normal to me. I guess it could be the problem with the transformation files. Could you please rerun on your uploaded dataset?
Thanks!
![image](https://github.com/user-attachments/assets/30ccd7f0-7631-48cd-af0b-02266895dee9)

**Comment by Duisterhof** [comment]
Hello,

Thanks for letting me know! Did you only run the coarse stage? This means all Gaussians are static so indeed the results might be quite bad.

**Comment by GostInShell** [comment]
My mistake. I thought the coarse stage is trained only on the first frame. The results in the fine stage seems normals.
Thanks for the answer!
